// Mock Premier League data for development and testing
// This simulates the response from football-data.org API

export const mockStandings = [
  {
    position: 1,
    id: 65,
    name: 'Manchester City',
    shortName: 'MCI',
    playedGames: 18,
    won: 14,
    draw: 2,
    lost: 2,
    points: 44,
    goalsFor: 47,
    goalsAgainst: 18,
    goalDifference: 29,
  },
  {
    position: 2,
    id: 64,
    name: 'Liverpool',
    shortName: 'LIV',
    playedGames: 18,
    won: 13,
    draw: 3,
    lost: 2,
    points: 42,
    goalsFor: 45,
    goalsAgainst: 19,
    goalDifference: 26,
  },
  {
    position: 3,
    id: 57,
    name: 'Arsenal',
    shortName: 'ARS',
    playedGames: 18,
    won: 12,
    draw: 2,
    lost: 4,
    points: 38,
    goalsFor: 41,
    goalsAgainst: 22,
    goalDifference: 19,
  },
  {
    position: 4,
    id: 61,
    name: 'Chelsea',
    shortName: 'CHE',
    playedGames: 18,
    won: 10,
    draw: 2,
    lost: 6,
    points: 32,
    goalsFor: 36,
    goalsAgainst: 28,
    goalDifference: 8,
  },
  {
    position: 5,
    id: 397,
    name: 'Brighton & Hove Albion',
    shortName: 'BHA',
    playedGames: 18,
    won: 9,
    draw: 4,
    lost: 5,
    points: 31,
    goalsFor: 33,
    goalsAgainst: 27,
    goalDifference: 6,
  },
  {
    position: 6,
    id: 73,
    name: 'Tottenham Hotspur',
    shortName: 'TOT',
    playedGames: 18,
    won: 9,
    draw: 2,
    lost: 7,
    points: 29,
    goalsFor: 35,
    goalsAgainst: 30,
    goalDifference: 5,
  },
  {
    position: 7,
    id: 58,
    name: 'Aston Villa',
    shortName: 'AVL',
    playedGames: 18,
    won: 8,
    draw: 4,
    lost: 6,
    points: 28,
    goalsFor: 30,
    goalsAgainst: 25,
    goalDifference: 5,
    last6Points: 7,
  },
  {
    position: 8,
    id: 66,
    name: 'Manchester United',
    shortName: 'MUN',
    playedGames: 18,
    won: 8,
    draw: 3,
    lost: 7,
    points: 27,
    goalsFor: 28,
    goalsAgainst: 28,
    goalDifference: 0,
  },
  {
    position: 9,
    id: 67,
    name: 'Newcastle United',
    shortName: 'NEW',
    playedGames: 18,
    won: 8,
    draw: 1,
    lost: 9,
    points: 25,
    goalsFor: 30,
    goalsAgainst: 32,
    goalDifference: -2,
  },
  {
    position: 10,
    id: 402,
    name: 'Brentford',
    shortName: 'BRE',
    playedGames: 18,
    won: 7,
    draw: 3,
    lost: 8,
    points: 24,
    goalsFor: 28,
    goalsAgainst: 30,
    goalDifference: -2,
  },
  {
    position: 11,
    id: 63,
    name: 'Fulham',
    shortName: 'FUL',
    playedGames: 18,
    won: 6,
    draw: 4,
    lost: 8,
    points: 22,
    goalsFor: 24,
    goalsAgainst: 28,
    goalDifference: -4,
  },
  {
    position: 12,
    id: 354,
    name: 'Crystal Palace',
    shortName: 'CRY',
    playedGames: 18,
    won: 6,
    draw: 2,
    lost: 10,
    points: 20,
    goalsFor: 22,
    goalsAgainst: 30,
    goalDifference: -8,
  },
  {
    position: 13,
    id: 76,
    name: 'Wolverhampton Wanderers',
    shortName: 'WOL',
    playedGames: 18,
    won: 5,
    draw: 4,
    lost: 9,
    points: 19,
    goalsFor: 20,
    goalsAgainst: 28,
    goalDifference: -8,
  },
  {
    position: 14,
    id: 563,
    name: 'West Ham United',
    shortName: 'WHU',
    playedGames: 18,
    won: 5,
    draw: 2,
    lost: 11,
    points: 17,
    goalsFor: 21,
    goalsAgainst: 33,
    goalDifference: -12,
  },
  {
    position: 15,
    id: 62,
    name: 'Everton',
    shortName: 'EVE',
    playedGames: 18,
    won: 4,
    draw: 4,
    lost: 10,
    points: 16,
    goalsFor: 18,
    goalsAgainst: 30,
    goalDifference: -12,
  },
  {
    position: 16,
    id: 341,
    name: 'Leeds United',
    shortName: 'LEE',
    playedGames: 18,
    won: 4,
    draw: 3,
    lost: 11,
    points: 15,
    goalsFor: 17,
    goalsAgainst: 32,
    goalDifference: -15,
  },
  {
    position: 17,
    id: 328,
    name: 'Burnley',
    shortName: 'BUR',
    playedGames: 18,
    won: 4,
    draw: 2,
    lost: 12,
    points: 14,
    goalsFor: 16,
    goalsAgainst: 34,
    goalDifference: -18,
  },
  {
    position: 18,
    id: 351,
    name: 'Nottingham Forest',
    shortName: 'NFO',
    playedGames: 18,
    won: 3,
    draw: 3,
    lost: 12,
    points: 12,
    goalsFor: 14,
    goalsAgainst: 35,
    goalDifference: -21,
  },
  {
    position: 19,
    id: 71,
    name: 'Sunderland',
    shortName: 'SUN',
    playedGames: 18,
    won: 2,
    draw: 2,
    lost: 14,
    points: 8,
    goalsFor: 12,
    goalsAgainst: 38,
    goalDifference: -26,
  },
  {
    position: 20,
    id: 1044,
    name: 'AFC Bournemouth',
    shortName: 'BOU',
    playedGames: 18,
    won: 1,
    draw: 2,
    lost: 15,
    points: 5,
    goalsFor: 10,
    goalsAgainst: 40,
    goalDifference: -30,
  },
];

export const mockFixtures = [
  { homeTeam: { id: 65, name: 'Manchester City' }, awayTeam: { id: 64, name: 'Liverpool' }, status: 'SCHEDULED', date: '2026-01-15' },
  { homeTeam: { id: 57, name: 'Arsenal' }, awayTeam: { id: 61, name: 'Chelsea' }, status: 'SCHEDULED', date: '2026-01-15' },
  { homeTeam: { id: 397, name: 'Brighton & Hove Albion' }, awayTeam: { id: 73, name: 'Tottenham Hotspur' }, status: 'SCHEDULED', date: '2026-01-16' },
  { homeTeam: { id: 341, name: 'Leeds United' }, awayTeam: { id: 58, name: 'Aston Villa' }, status: 'SCHEDULED', date: '2026-01-18' },
  { homeTeam: { id: 66, name: 'Manchester United' }, awayTeam: { id: 67, name: 'Newcastle United' }, status: 'SCHEDULED', date: '2026-01-18' },
  { homeTeam: { id: 402, name: 'Brentford' }, awayTeam: { id: 63, name: 'Fulham' }, status: 'SCHEDULED', date: '2026-01-19' },
  { homeTeam: { id: 354, name: 'Crystal Palace' }, awayTeam: { id: 76, name: 'Wolverhampton Wanderers' }, status: 'SCHEDULED', date: '2026-01-20' },
  { homeTeam: { id: 563, name: 'West Ham United' }, awayTeam: { id: 62, name: 'Everton' }, status: 'SCHEDULED', date: '2026-01-20' },
  { homeTeam: { id: 328, name: 'Burnley' }, awayTeam: { id: 351, name: 'Nottingham Forest' }, status: 'SCHEDULED', date: '2026-01-21' },
  { homeTeam: { id: 71, name: 'Sunderland' }, awayTeam: { id: 1044, name: 'AFC Bournemouth' }, status: 'SCHEDULED', date: '2026-01-21' },
  // More fixtures would continue...
];

export const useMockData = import.meta.env.VITE_USE_MOCK_DATA === 'true';

export async function getMockStandings() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({ teams: mockStandings });
    }, 300); // Simulate network delay
  });
}

export async function getMockFixtures() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({ fixtures: mockFixtures });
    }, 300); // Simulate network delay
  });
}
